version: '3.5'

services:
  peak-frontend_web:
    image: nginx:stable-alpine
    ports:
      - 80:80
    container_name: 'peak-frontend_web'
    restart: unless-stopped
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - /data/images:/data/images
      - /data/pdf:/data/pdf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
